export interface Company {
  id: string
  name: string
  logo: string
  industry: string
  location: string
  description: string
  openRoles: number
}

export interface Role {
  id: string
  companyId: string
  title: string
  department: string
  type: string
  location: string
  salary: string
  description: string
  requirements: string[]
}

export interface Candidate {
  id: string
  name: string
  email: string
  phone: string
  appliedRole: string
  company: string
  experience: string
  education: string
  skills: string[]
  resumeFile: string
  appliedDate: string
  status: "New" | "Reviewed" | "Shortlisted" | "Rejected"
}

export const companies: Company[] = [
  {
    id: "1",
    name: "TechNova Solutions",
    logo: "TN",
    industry: "Software & Technology",
    location: "San Francisco, CA",
    description: "Building next-generation cloud infrastructure and developer tools that power modern applications.",
    openRoles: 5,
  },
  {
    id: "2",
    name: "GreenLeaf Analytics",
    logo: "GA",
    industry: "Data & Analytics",
    location: "New York, NY",
    description: "Transforming raw data into actionable insights with cutting-edge machine learning solutions.",
    openRoles: 3,
  },
  {
    id: "3",
    name: "Meridian Health",
    logo: "MH",
    industry: "Healthcare Tech",
    location: "Boston, MA",
    description: "Revolutionizing patient care through innovative digital health platforms and telemedicine.",
    openRoles: 4,
  },
  {
    id: "4",
    name: "UrbanPulse",
    logo: "UP",
    industry: "Smart Cities",
    location: "Austin, TX",
    description: "Creating intelligent urban solutions for sustainable and connected city living.",
    openRoles: 2,
  },
  {
    id: "5",
    name: "FinEdge Capital",
    logo: "FE",
    industry: "FinTech",
    location: "Chicago, IL",
    description: "Democratizing financial services with AI-powered investment and banking platforms.",
    openRoles: 6,
  },
  {
    id: "6",
    name: "NexGen Robotics",
    logo: "NR",
    industry: "Robotics & AI",
    location: "Seattle, WA",
    description: "Pioneering autonomous systems and robotics for industrial and consumer applications.",
    openRoles: 3,
  },
]

export const roles: Role[] = [
  // TechNova Solutions
  {
    id: "r1",
    companyId: "1",
    title: "Senior Frontend Engineer",
    department: "Engineering",
    type: "Full-time",
    location: "San Francisco, CA (Hybrid)",
    salary: "$150K - $190K",
    description: "Build and maintain our core UI platform using React and TypeScript.",
    requirements: ["5+ years React", "TypeScript", "System design", "CI/CD experience"],
  },
  {
    id: "r2",
    companyId: "1",
    title: "Backend Engineer",
    department: "Engineering",
    type: "Full-time",
    location: "Remote",
    salary: "$140K - $180K",
    description: "Design and build scalable microservices powering our cloud platform.",
    requirements: ["Go or Rust", "Distributed systems", "PostgreSQL", "Kubernetes"],
  },
  {
    id: "r3",
    companyId: "1",
    title: "Product Designer",
    department: "Design",
    type: "Full-time",
    location: "San Francisco, CA",
    salary: "$130K - $165K",
    description: "Shape the user experience of our developer tools and dashboard interfaces.",
    requirements: ["Figma mastery", "Design systems", "User research", "Prototyping"],
  },
  {
    id: "r4",
    companyId: "1",
    title: "DevOps Engineer",
    department: "Infrastructure",
    type: "Full-time",
    location: "Remote",
    salary: "$145K - $185K",
    description: "Build and optimize CI/CD pipelines and cloud infrastructure.",
    requirements: ["AWS/GCP", "Terraform", "Docker", "Monitoring tools"],
  },
  {
    id: "r5",
    companyId: "1",
    title: "Technical Writer",
    department: "Documentation",
    type: "Contract",
    location: "Remote",
    salary: "$80K - $110K",
    description: "Create clear, comprehensive documentation for our developer tools and APIs.",
    requirements: ["Technical writing", "API docs", "Markdown", "Developer tools experience"],
  },
  // GreenLeaf Analytics
  {
    id: "r6",
    companyId: "2",
    title: "Data Scientist",
    department: "Data Science",
    type: "Full-time",
    location: "New York, NY",
    salary: "$160K - $200K",
    description: "Develop ML models for predictive analytics and data insights.",
    requirements: ["Python", "TensorFlow/PyTorch", "Statistics", "SQL"],
  },
  {
    id: "r7",
    companyId: "2",
    title: "ML Engineer",
    department: "Engineering",
    type: "Full-time",
    location: "New York, NY (Hybrid)",
    salary: "$155K - $195K",
    description: "Build production ML pipelines and deploy models at scale.",
    requirements: ["MLOps", "Python", "Spark", "Cloud platforms"],
  },
  {
    id: "r8",
    companyId: "2",
    title: "Analytics Consultant",
    department: "Consulting",
    type: "Full-time",
    location: "Remote",
    salary: "$120K - $155K",
    description: "Partner with clients to implement data-driven strategies.",
    requirements: ["Data visualization", "SQL", "Stakeholder management", "Business acumen"],
  },
  // Meridian Health
  {
    id: "r9",
    companyId: "3",
    title: "Full Stack Developer",
    department: "Engineering",
    type: "Full-time",
    location: "Boston, MA",
    salary: "$135K - $170K",
    description: "Build patient-facing applications and internal health platforms.",
    requirements: ["React", "Node.js", "HIPAA compliance", "REST APIs"],
  },
  {
    id: "r10",
    companyId: "3",
    title: "QA Engineer",
    department: "Quality",
    type: "Full-time",
    location: "Boston, MA (Hybrid)",
    salary: "$100K - $135K",
    description: "Ensure quality and reliability of healthcare software products.",
    requirements: ["Test automation", "Selenium", "Agile", "Healthcare domain"],
  },
  {
    id: "r11",
    companyId: "3",
    title: "Clinical Data Analyst",
    department: "Data",
    type: "Full-time",
    location: "Remote",
    salary: "$110K - $145K",
    description: "Analyze clinical trial data and generate actionable health insights.",
    requirements: ["R/Python", "Clinical data", "Statistical analysis", "Reporting"],
  },
  {
    id: "r12",
    companyId: "3",
    title: "UX Researcher",
    department: "Design",
    type: "Contract",
    location: "Boston, MA",
    salary: "$95K - $125K",
    description: "Conduct user research to improve patient and provider experiences.",
    requirements: ["User interviews", "Usability testing", "Survey design", "Healthcare UX"],
  },
  // UrbanPulse
  {
    id: "r13",
    companyId: "4",
    title: "IoT Engineer",
    department: "Engineering",
    type: "Full-time",
    location: "Austin, TX",
    salary: "$130K - $165K",
    description: "Design and deploy IoT sensor networks for smart city infrastructure.",
    requirements: ["Embedded systems", "C/C++", "MQTT", "Edge computing"],
  },
  {
    id: "r14",
    companyId: "4",
    title: "Urban Planner (Tech)",
    department: "Strategy",
    type: "Full-time",
    location: "Austin, TX",
    salary: "$100K - $130K",
    description: "Bridge urban planning expertise with technology-driven city solutions.",
    requirements: ["Urban planning", "GIS", "Data analysis", "Stakeholder engagement"],
  },
  // FinEdge Capital
  {
    id: "r15",
    companyId: "5",
    title: "Blockchain Developer",
    department: "Engineering",
    type: "Full-time",
    location: "Chicago, IL",
    salary: "$160K - $210K",
    description: "Build decentralized financial products on blockchain platforms.",
    requirements: ["Solidity", "Web3.js", "DeFi protocols", "Smart contracts"],
  },
  {
    id: "r16",
    companyId: "5",
    title: "Risk Analyst",
    department: "Finance",
    type: "Full-time",
    location: "Chicago, IL (Hybrid)",
    salary: "$110K - $145K",
    description: "Assess and manage financial risk using quantitative models.",
    requirements: ["Risk modeling", "Python/R", "Financial markets", "Regulatory compliance"],
  },
  {
    id: "r17",
    companyId: "5",
    title: "Product Manager",
    department: "Product",
    type: "Full-time",
    location: "Remote",
    salary: "$140K - $180K",
    description: "Drive product strategy for consumer-facing fintech applications.",
    requirements: ["Product roadmaps", "Agile", "User stories", "Market analysis"],
  },
  {
    id: "r18",
    companyId: "5",
    title: "Security Engineer",
    department: "Security",
    type: "Full-time",
    location: "Chicago, IL",
    salary: "$155K - $200K",
    description: "Protect financial systems and user data through robust security practices.",
    requirements: ["Penetration testing", "SIEM", "Compliance (SOC 2)", "Cloud security"],
  },
  {
    id: "r19",
    companyId: "5",
    title: "Mobile Developer",
    department: "Engineering",
    type: "Full-time",
    location: "Remote",
    salary: "$135K - $175K",
    description: "Build and maintain cross-platform mobile banking applications.",
    requirements: ["React Native", "iOS/Android", "REST APIs", "Performance optimization"],
  },
  {
    id: "r20",
    companyId: "5",
    title: "Customer Success Manager",
    department: "Operations",
    type: "Full-time",
    location: "Chicago, IL",
    salary: "$90K - $120K",
    description: "Ensure client satisfaction and drive adoption of our financial products.",
    requirements: ["Client management", "FinTech knowledge", "Communication", "CRM tools"],
  },
  // NexGen Robotics
  {
    id: "r21",
    companyId: "6",
    title: "Robotics Software Engineer",
    department: "Engineering",
    type: "Full-time",
    location: "Seattle, WA",
    salary: "$155K - $200K",
    description: "Develop control software for autonomous robotic systems.",
    requirements: ["ROS", "C++", "Computer vision", "Motion planning"],
  },
  {
    id: "r22",
    companyId: "6",
    title: "Computer Vision Engineer",
    department: "AI/ML",
    type: "Full-time",
    location: "Seattle, WA",
    salary: "$160K - $205K",
    description: "Build perception systems for autonomous navigation and object recognition.",
    requirements: ["OpenCV", "Deep learning", "Python/C++", "3D vision"],
  },
  {
    id: "r23",
    companyId: "6",
    title: "Hardware Engineer",
    department: "Hardware",
    type: "Full-time",
    location: "Seattle, WA",
    salary: "$140K - $180K",
    description: "Design and prototype robotic hardware components and sensor assemblies.",
    requirements: ["PCB design", "CAD", "Sensor integration", "Prototyping"],
  },
]

export const candidates: Candidate[] = [
  {
    id: "c1",
    name: "Alex Johnson",
    email: "alex.johnson@email.com",
    phone: "(555) 123-4567",
    appliedRole: "Senior Frontend Engineer",
    company: "TechNova Solutions",
    experience: "6 years",
    education: "B.S. Computer Science, Stanford University",
    skills: ["React", "TypeScript", "Next.js", "GraphQL", "Tailwind CSS"],
    resumeFile: "alex_johnson_resume.pdf",
    appliedDate: "2026-02-18",
    status: "New",
  },
  {
    id: "c2",
    name: "Maria Garcia",
    email: "maria.garcia@email.com",
    phone: "(555) 234-5678",
    appliedRole: "Data Scientist",
    company: "GreenLeaf Analytics",
    experience: "4 years",
    education: "M.S. Data Science, MIT",
    skills: ["Python", "TensorFlow", "SQL", "Statistics", "Tableau"],
    resumeFile: "maria_garcia_resume.pdf",
    appliedDate: "2026-02-17",
    status: "Reviewed",
  },
  {
    id: "c3",
    name: "James Wilson",
    email: "james.wilson@email.com",
    phone: "(555) 345-6789",
    appliedRole: "Full Stack Developer",
    company: "Meridian Health",
    experience: "5 years",
    education: "B.S. Software Engineering, Georgia Tech",
    skills: ["React", "Node.js", "PostgreSQL", "Docker", "AWS"],
    resumeFile: "james_wilson_resume.pdf",
    appliedDate: "2026-02-16",
    status: "Shortlisted",
  },
  {
    id: "c4",
    name: "Sarah Chen",
    email: "sarah.chen@email.com",
    phone: "(555) 456-7890",
    appliedRole: "Product Designer",
    company: "TechNova Solutions",
    experience: "7 years",
    education: "MFA Design, Rhode Island School of Design",
    skills: ["Figma", "User Research", "Prototyping", "Design Systems", "Adobe CC"],
    resumeFile: "sarah_chen_resume.pdf",
    appliedDate: "2026-02-15",
    status: "Reviewed",
  },
  {
    id: "c5",
    name: "Raj Patel",
    email: "raj.patel@email.com",
    phone: "(555) 567-8901",
    appliedRole: "Backend Engineer",
    company: "TechNova Solutions",
    experience: "8 years",
    education: "M.S. Computer Science, Carnegie Mellon",
    skills: ["Go", "Rust", "Kubernetes", "PostgreSQL", "gRPC"],
    resumeFile: "raj_patel_resume.pdf",
    appliedDate: "2026-02-14",
    status: "New",
  },
  {
    id: "c6",
    name: "Emily Rodriguez",
    email: "emily.rodriguez@email.com",
    phone: "(555) 678-9012",
    appliedRole: "ML Engineer",
    company: "GreenLeaf Analytics",
    experience: "3 years",
    education: "Ph.D. Machine Learning, UC Berkeley",
    skills: ["PyTorch", "MLOps", "Spark", "Python", "Kubernetes"],
    resumeFile: "emily_rodriguez_resume.pdf",
    appliedDate: "2026-02-13",
    status: "Shortlisted",
  },
  {
    id: "c7",
    name: "David Kim",
    email: "david.kim@email.com",
    phone: "(555) 789-0123",
    appliedRole: "Blockchain Developer",
    company: "FinEdge Capital",
    experience: "4 years",
    education: "B.S. Computer Science, UCLA",
    skills: ["Solidity", "Web3.js", "Ethereum", "Smart Contracts", "TypeScript"],
    resumeFile: "david_kim_resume.pdf",
    appliedDate: "2026-02-12",
    status: "New",
  },
  {
    id: "c8",
    name: "Priya Sharma",
    email: "priya.sharma@email.com",
    phone: "(555) 890-1234",
    appliedRole: "Robotics Software Engineer",
    company: "NexGen Robotics",
    experience: "5 years",
    education: "M.S. Robotics, University of Michigan",
    skills: ["ROS", "C++", "Python", "Computer Vision", "Motion Planning"],
    resumeFile: "priya_sharma_resume.pdf",
    appliedDate: "2026-02-11",
    status: "Reviewed",
  },
  {
    id: "c9",
    name: "Michael Brown",
    email: "michael.brown@email.com",
    phone: "(555) 901-2345",
    appliedRole: "IoT Engineer",
    company: "UrbanPulse",
    experience: "6 years",
    education: "B.S. Electrical Engineering, Purdue University",
    skills: ["Embedded Systems", "C/C++", "MQTT", "Edge Computing", "PCB Design"],
    resumeFile: "michael_brown_resume.pdf",
    appliedDate: "2026-02-10",
    status: "New",
  },
  {
    id: "c10",
    name: "Lisa Wang",
    email: "lisa.wang@email.com",
    phone: "(555) 012-3456",
    appliedRole: "Security Engineer",
    company: "FinEdge Capital",
    experience: "7 years",
    education: "M.S. Cybersecurity, Johns Hopkins",
    skills: ["Penetration Testing", "SIEM", "SOC 2", "Cloud Security", "Incident Response"],
    resumeFile: "lisa_wang_resume.pdf",
    appliedDate: "2026-02-09",
    status: "Shortlisted",
  },
]
